### ISSUE TITLE
Error with WebWorkers

### ISSUE THREAD

**Issue by timokoch** [InsightSoftwareConsortium/craco-itk#3]
I installed the sample app (test-app, git@master). It starts up / compiles fine but when I upload a sample file, e.g. the 'cow.vtp' file from the vtk.js docs, I get the following error:

```
SecurityError: Failed to construct 'Worker': Script at 'http://itk/WebWorkers/Pipeline.worker.js' cannot be accessed from origin 'http://localhost:3000'.
▼ 3 stack frames were expanded.
createWebworkerPromise
node_modules/itk/createWebworkerPromise.js:31
readPolyDataFile
node_modules/itk/readPolyDataFile.js:11
readFile
node_modules/itk/readFile.js:19
▲ 3 stack frames were expanded.
App.processFile
src/App.js:26
  23 | 
  24 | const app = this
  25 | console.log(files[0])
> 26 | return readFile(null, files[0]).then(function({ image, mesh, webWorker }) {
     | ^  27 |   webWorker.terminate();
  28 |   const imageOrMesh = image || mesh
  29 | 
View compiled
▶ 22 stack frames were collapsed.
```

The URL of the ITK script for the web worker seems wrong? Probably shouldn't have a "http://" prefix or is that correct? 
I have the same error in another sample application of mine where I used craco-itk.

I use Chrome if that matters. Any ideas or pointers how to solve this?

**Comment by thewtex** [comment]
`.vtp` support comes through the more recently added itk.js "PolyData" IO support -- the test app is updated to enable this in https://github.com/InsightSoftwareConsortium/craco-itk/pull/4

**Comment by timokoch** [comment]
ok thank you so much it works now. Can you comment on where the error comes/came from? That would help me with the same error in my other app where I don't have this line.

**Comment by thewtex** [comment]
@timokoch excellent!

"PolyData" IO is relatively recent, currently supporting these file formats:

  https://insightsoftwareconsortium.github.io/itk-js/docs/polydata_formats.html

It looks like the poly data support was missing from the `readFile` docs -- added here: https://github.com/InsightSoftwareConsortium/itk-js/pull/362

**Comment by timokoch** [comment]
@thewtex Thanks for adding doc. That's appreciated. What I still don't understand is why this resulted in the WebWorker error? Because in #4 you didn't change anything about `readFile`, you just seem to look for an additional arguments in the promise response.

**Comment by thewtex** [comment]
The WebWorker error could be because your local build may not have the latest version of `craco-itk`, which adds https://github.com/InsightSoftwareConsortium/craco-itk/commit/6cbbc57157fda20abd374e6963ecc72c1e76ffc8

**Comment by timokoch** [comment]
@thewtex I have `craco-itk v1.0.1`. After a long debug session I found out how to reproduce the error. If I do

```
git clone https://github.com/InsightSoftwareConsortium/craco-itk.git
cd craco-itk/test-app
yarn install && yarn start
```

everything works. However when I delete the `yarn.lock` file
```
git clone https://github.com/InsightSoftwareConsortium/craco-itk.git
cd craco-itk/test-app
rm yarn.lock
yarn install && yarn start
```

I start getting the WebWorker error. There seems to be some dependency locked that is required but not listed in the `package.json`. Do you know what that dependency might be? Or what might be the issue here?

In my other project I just followed the README and installed craco-itk, so there I don't have the same `yarn.lock` as for the sample app. And I always get the WebWorker error, even if I reduce the app to exactly the `test-app`, but of course  `yarn.lock` will be different...

**Comment by timokoch** [comment]
I was under the wrong impression that #4 fixed my error because I apparently switched from `npm` to `yarn` to build the test app after I pulled the changes. For `npm` I still get the WebWorker error because of course it doesn't care about the `yarn.lock`. So maybe this issue should be reopened?

**Comment by thewtex** [comment]
@timokoch thanks for the follow-up. :1st_place_medal: 

Yes, something new in the dependency tree update seems to be unhappy with how the files are now served. This is a separate issue as far as I can tell.

I reproduced the behaviour following your notes, and this fix resolved the issue: https://github.com/InsightSoftwareConsortium/craco-itk/commit/aea979166aa564dced1aff498caf411292c96641

Please try `craco-itk 1.0.5` and let us know how it goes.

**Comment by timokoch** [comment]
@thewtex awesome it works now 👍
